### ISSUE TITLE
git-shell-commands key-add error

### ISSUE THREAD

**Issue by Nalic** [emaV/WDMyCloud-git-shell-commands#1]
Thank you for the tools！

according to README,  exec command ./git-shell-commands/key-add
but  I failed....

Input the key to be added:
ssh-rsa AAA ************* p8aMN/r43er0SRoUv1hwcOst3TJqRyOQiiARA33aBmk2yinSvXwXd1xJ7ad5QEiUN8TgYA/hHfiHE6hKYOV+iXWMiXVnfr6ZjjdUevpckeZ42423LwT6jyABALi80R4VE7T+VoTseJzPJG//IpNFrzRuBCi21Czv3XwjXqT9Mo+dizm/jufsHFQ4QYJYpOKaul7GVMyMLz+qSLmE2beC8+DWgLbBcCLwQNn9gM2p/halHcq7FGB/W/D9vavE+beQH8AoZd8ESpV3w== nlc@wd
Error: 4096 SHA256:dqBsRXMvGwZDRAytz3etwV8tS6Tssq8wjW+hjUxbJ6U

what should I do in this step？ thanks。

**Comment by emaV** [comment]
Hey Nalic, thank you!

Ok, it seems that your WD model use a different `ssh-keygen`. I read something about and I had to change the code to manage my version that get and test fingerprint like:

    4096 c8:22:69:4a:ae:49:4b:83:47:d6:d6:b2:c1:99:0f:06

To match a different format you should modify the line 25 in [key-add](https://github.com/emaV/WDMyCloud-git-shell-commands/blob/87964b567acbee0066bae8120dbb375de8ab1a0a/key-add#L25) file.

You can try with something like:

    if [ $(echo "$fingerprint" | egrep -c '[0-9]+ SHA256:([0-9A-Za-z])+') -eq 0 ]

I currently don't have access to a WD device so I cannot help more

**Comment by Nalic** [comment]
Perfect ， the problem has been fixed， thank you！ emaV .
